# Generated by Django 3.2.8 on 2021-11-10 06:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('measurement_unit', models.CharField(choices=[('шт.', 'шт.'), ('звездочка', 'звездочка'), ('г', 'г'), ('пучок', 'пучок'), ('по вкусу', 'по вкусу'), ('мл', 'мл'), ('стакан', 'стакан'), ('кусок', 'кусок'), ('пакет', 'пакет'), ('долька', 'долька'), ('упаковка', 'упаковка'), ('щепотка', 'щепотка'), ('стручок', 'стручок'), ('зубчик', 'зубчик'), ('банка', 'банка'), ('стебель', 'стебель'), ('веточка', 'веточка'), ('кг', 'кг'), ('тушка', 'тушка'), ('лист', 'лист'), ('пласт', 'пласт'), ('горсть', 'горсть'), ('ч. л.', 'ч. л.'), ('капля', 'капля'), ('пачка', 'пачка'), ('л', 'л'), ('ст. л.', 'ст. л.'), ('пакетик', 'пакетик'), ('батон', 'батон'), ('бутылка', 'бутылка')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('cooking_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('#000000', 'Черный'), ('#808080', 'Серый'), ('#c0c0c0', 'Серебряный'), ('#ffffff', 'Белый'), ('#ff00ff', 'Фуксия'), ('#800080', 'Пурпурный'), ('#ff0000', 'Красный'), ('#800000', 'Коричнево-малиновый'), ('#ffff00', 'Жёлтый'), ('#808000', 'Оливковый'), ('#00ff00', 'Лайм'), ('#008000', 'Зелёный'), ('#00ffff', 'Цвет морской волны'), ('#008080', 'Окраски птицы чирок'), ('#0000ff', 'Синий'), ('#000080', 'Форма морских офицеров')], max_length=100)),
                ('slug', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingedients', to='recipes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipes.Tag'),
        ),
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='CartShopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_cart', to='recipes.recipe')),
            ],
        ),
    ]
